name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace Access Tokens
        run: |
          sed -i 's/JAWG_ACCESS_TOKEN_PLACEHOLDER/${{ secrets.JAWG_ACCESS_TOKEN }}/g' js/map.js
          sed -i 's/MAPBOX_ACCESS_TOKEN_PLACEHOLDER/${{ secrets.MAPBOX_ACCESS_TOKEN }}/g' js/map.js

      - name: Verify Replacement
        run: cat js/map.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true